services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: oasisflow
      MYSQL_USER: oasisflow
      MYSQL_PASSWORD: oasisflow
      MYSQL_DATABASE: oasisflow
    ports:
      - "3306:3306"
    volumes:
      - oasisflow_mysql_data:/var/lib/mysql

volumes:
  oasisflow_mysql_data:
